import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  cheatsheetSidebar: [{type: 'autogenerated', dirName: 'cheatsheet'}],
  methodologieSidebar: [{type: 'autogenerated', dirName: 'methodologie'}],
};

export default sidebars;
